# Generated by Django 6.0.1 on 2026-01-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='tipo_cliente',
            field=models.CharField(choices=[('minorista', 'Minorista'), ('mayorista', 'Mayorista'), ('restaurante', 'Restaurante'), ('bar', 'Bar')], max_length=20),
        ),
    ]
