# Generated by Django 6.0.1 on 2026-01-17 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=20, null=True)),
                ('nit', models.CharField(max_length=20, null=True)),
                ('tipo_cliente', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido1', models.CharField(max_length=50, null=True)),
                ('apellido2', models.CharField(max_length=50, null=True)),
                ('direccion', models.CharField(max_length=200, null=True)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=20)),
                ('fecha_emision', models.DateField()),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Importaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.BooleanField()),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Metodos_Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20)),
                ('tipo_preedor', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido1', models.CharField(max_length=50, null=True)),
                ('apellido2', models.CharField(max_length=50, null=True)),
                ('pais', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('detalle', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categorías de Productos',
            },
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='detalleimportacion',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='detalleimportacion',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='venta',
        ),
        migrations.RemoveField(
            model_name='importacionlote',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='importacionlote',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='vendedor',
        ),
        migrations.CreateModel(
            name='Devoluciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('eatado', models.BooleanField()),
                ('motivo', models.CharField(max_length=150)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura_registro', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.facturas')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia_transaccion', models.CharField(max_length=50)),
                ('metodo_pago_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.metodos_pago')),
                ('pago_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.pagos')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('nombre', models.CharField(max_length=80)),
                ('marca', models.CharField(max_length=50)),
                ('origen', models.CharField(max_length=50)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.categorias')),
                ('proveedor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.proveedores')),
                ('ubicacion_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Importaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.importaciones')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Devoluciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('observacion', models.CharField(max_length=150)),
                ('devolucion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.devoluciones')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.productos')),
            ],
        ),
        migrations.AddField(
            model_name='importaciones',
            name='proveedor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.proveedores'),
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_premiso', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('rol_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('clave', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido1', models.CharField(max_length=50)),
                ('Apellido2', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=150)),
                ('estado', models.BooleanField()),
                ('rol_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.roles')),
            ],
        ),
        migrations.AddField(
            model_name='importaciones',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.usuarios'),
        ),
        migrations.AddField(
            model_name='devoluciones',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.usuarios'),
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('accion', models.CharField(max_length=100)),
                ('detalle', models.CharField(max_length=200)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.BooleanField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.clientes')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='facturas',
            name='venta_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ventas'),
        ),
        migrations.AddField(
            model_name='devoluciones',
            name='venta_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ventas'),
        ),
        migrations.CreateModel(
            name='Detalle_Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.productos')),
                ('venta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ventas')),
            ],
        ),
        migrations.DeleteModel(
            name='CategoriaProducto',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='DetalleImportacion',
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
        migrations.DeleteModel(
            name='ImportacionLote',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
