# Generated by Django 6.0.1 on 2026-01-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_usuario_email_remove_usuario_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacion',
            name='stock_ingresado',
            field=models.BooleanField(default=False),
        ),
    ]
