# Generated by Django 6.0.1 on 2026-01-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_importacion_stock_ingresado'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(blank=True, to='dashboard.permiso'),
        ),
    ]
