# Generated by Django 6.0.1 on 2026-01-20 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_importaciones',
            name='producto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.productos'),
        ),
    ]
