# Generated by Django 6.0.1 on 2026-01-20 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importaciones',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalle_importaciones',
            name='importacion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.importaciones'),
        ),
        migrations.AddField(
            model_name='importaciones',
            name='proveedor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.proveedores'),
        ),
    ]
