# Generated by Django 6.0.1 on 2026-01-20 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='factura_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.facturas'),
        ),
        migrations.AddField(
            model_name='detalle_pagos',
            name='pago_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.pagos'),
        ),
    ]
