<<<<<<< HEAD
# Generated by Django 6.0.1 on 2026-01-25 23:00
=======
# Generated by Django 6.0.1 on 2026-01-22 12:56
>>>>>>> ae383f2b1472caffe190b1543f4264ded46aa5b7

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name': 'Roles', 'verbose_name_plural': 'Roles'},
        ),
    ]
