# Generated by Django 6.0.1 on 2026-01-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='fecha_emision',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='numero_factura',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
